apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    name: postgres-deployment
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres
      tier: backend
  template:
    metadata:
      name: postgres
      labels:
        name: postgres
        tier: backend
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
