apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app
      tier: frontend
  template:
    metadata:
      name: result-app
      labels:
        name: result-app
        tier: frontend
    spec:
      containers:
        - name: result-app
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
