apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-voting-app
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3
  selector:
    matchLabels: # matches Pod label
      type: front-end
